package com.oreilly.hh.dao;

import java.time.LocalTime;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


import com.oreilly.hh.data.Track;

@Repository
public interface TrackDAO extends JpaRepository<Track, Integer> {

    /* Methods autogenerated by Spring Data Jpa:
    Track       save(S entity);
    List<Track> saveAll(Iterable<S> entities);

    void        delete(T entity);
    void        deleteById(ID id)
    void        deleteAll()

    Optional<T> findById(ID primaryKey);
    Iterable<T> findAll();
    Iterable<T> findAllById(Iterable<ID> ids);
    */

    /* Autogenerated by User request */
    List<Track> findByPlayTimeLessThanEqual(LocalTime length);

}

